### ISSUE TITLE
Configuration Option to Clear Terminal Between Test Runs

### ISSUE THREAD

**Issue by dhakiki** [tertestrial/roadmap#2]
I'd like a configuration option to clear the terminal between test runs. For some, having the last run's information intact may be useful, but for me, I can do without it!

**Comment by kevgo** [comment]
This method seems to work on macOS: https://phoenixnap.com/kb/clear-terminal#:~:text=Method%204%3A%20Clear%20Terminal%20via%20alias%20Command,-Alternative%20methods%20for&text=For%20instance%2C%20the%20%5C033%20is,the%20command%20clears%20the%20terminal.&text=The%20command%20clears%20the%20terminal%20screen%2C%20including%20the%20scrollback%20buffer.

**Comment by dmh43** [comment]
what a blast from the past :v:
